export const samplePages = [
  { page_number: 1, title: "Two candles in the morning", body: "Maya woke to two golden sunbeams and two bright birthday candles waiting downstairs. Today she was two — a whole hand of tiny adventures older than yesterday.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 2, title: "Mum’s very favorite bag", body: "On the chair sat Mum’s raspberry handbag. Maya slipped the handles over her shoulder. The bag nearly reached her knees, which made her walk like a very important birthday explorer.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 3, title: "A little birthday sparkle", body: "At Mum’s mirror, Maya found the softest clean makeup brush. Brush-brush on one cheek. Brush-brush on the other. “Beautiful,” said Mum, though Maya’s happiest sparkle was already in her smile.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 4, title: "When she was very small", body: "Dad remembered the day Maya fit into the bend of his arm. Mum remembered her first sleepy yawn. They had watched every stretch, every giggle, and every brave little step.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 5, title: "Look how far you have come", body: "Once, Maya held one finger to stand. Now she carried handbags, chose her own shoes, and announced important things like, “I do it!” Her parents’ hearts grew right alongside her.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 6, title: "The grand birthday parade", body: "Maya marched through the house with the handbag swinging. Mum followed with ribbons. Dad followed with the cake. Even the moon seemed to follow, peeking through the window.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 7, title: "Their favorite wish", body: "Maya puffed at her candles. Her parents made a quiet wish too: that she would always know how loved she was — from her baby days, through today, and into every tomorrow.", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
  { page_number: 8, title: "A little more grown-up", body: "At bedtime, Mum tucked the handbag beside the bed. Dad tucked the blanket under Maya’s chin. “I’m big now,” Maya whispered. “A little,” they smiled. “And always our baby too.”", illustration_url: "/assets/birthday-story-scenes.png", narration_url: null },
];
